### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by fabiorinnone** [fabiorinnone/NetMatchStar#11]
An exception launched when it is launched WattsStrogatz model with no "Directed" option selected:

`
java.util.ConcurrentModificationException
java.lang.Exception: Please check data!
	at it.unict.dmi.netmatchstar.algorithm.metrics.MetricsTask.run(MetricsTask.java:351)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1184)
	at java.util.Vector$Itr.next(Vector.java:1137)
	at it.unict.dmi.netmatchstar.graph.Graph.removeEdge(Graph.java:222)
	at it.unict.dmi.netmatchstar.algorithm.significance.RandomGenerator.createWattsStrogatz(RandomGenerator.java:156)
	at it.unict.dmi.netmatchstar.algorithm.metrics.MetricsTask.run(MetricsTask.java:287)
`

Add a breakpoint in `RandomGenerator.java` line 148.

**Comment by fabiorinnone** [comment]
Check also ForestFire model.

**Comment by fabiorinnone** [comment]
Model affected are:

1. Watts-Strogatz
2. Duplication
3. Forest-fire

because they remove edges from graphs.

Issue is caused by `removeEdge` method of `Graph` class in block from line 215 to 231.
