### ISSUE TITLE
App description not found

### ISSUE THREAD

**Issue by fabiorinnone** [fabiorinnone/NetMatchStar#3]
Fix MANIFEST.MF.

**Comment by fabiorinnone** [comment]
Probably issue is related to following exception on installation:

`org.cytoscape.app.internal.exception.AppLoadingException: Class netmatch.NetMatchApp not found in URL: file:/home/fabior/CytoscapeConfiguration/3/apps/.temp-installed/netmatchstar.jar
	at org.cytoscape.app.internal.manager.SimpleApp.load(SimpleApp.java:144)
	at org.cytoscape.app.internal.manager.AppManager$1.onFileCreate(AppManager.java:460)
	at org.apache.commons.io.monitor.FileAlterationObserver.doCreate(FileAlterationObserver.java:379)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:345)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:304)
	at org.cytoscape.app.internal.manager.AppManager.checkForFileChanges(AppManager.java:737)
	at org.cytoscape.app.internal.manager.AppManager.installApp(AppManager.java:826)
	at org.cytoscape.app.internal.task.InstallAppsTask.run(InstallAppsTask.java:32)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:342)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: netmatch.NetMatchApp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.cytoscape.app.internal.manager.SimpleApp.load(SimpleApp.java:142)
	... 14 more
`
