### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by fabiorinnone** [fabiorinnone/NetMatchStar#9]
`java.lang.NullPointerException
java.lang.Exception: Please check data!
	at it.unict.dmi.netmatchstar.algorithm.significance.ShufflingTask.run(ShufflingTask.java:348)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at it.unict.dmi.netmatchstar.graph.Graph.inOutDegreePreservingShuffling(Graph.java:542)
	at it.unict.dmi.netmatchstar.algorithm.significance.ShufflingTask.run(ShufflingTask.java:228)`

Use following project file:

[test1.cys.zip](https://github.com/fabiorinnone/NetMatchStar/files/859815/test1.cys.zip)

**Comment by fabiorinnone** [comment]
Issue is caused by shuffling model if "Labeled" option is not selected in "Matching" panel.

**Comment by fabiorinnone** [comment]
Fixed by a workaround in `pickupEdge()` method of `Graph` class, but the following exception is yet launched when a metrics task starts:

`
java.util.ConcurrentModificationException
java.lang.Exception: Please check data!
	at it.unict.dmi.netmatchstar.algorithm.metrics.MetricsTask.run(MetricsTask.java:351)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1184)
	at java.util.Vector$Itr.next(Vector.java:1137)
	at it.unict.dmi.netmatchstar.graph.Graph.removeEdge(Graph.java:222)
	at it.unict.dmi.netmatchstar.algorithm.significance.RandomGenerator.createWattsStrogatz(RandomGenerator.java:156)
	at it.unict.dmi.netmatchstar.algorithm.metrics.MetricsTask.run(MetricsTask.java:287)
`
